version: "3"

# docker-compose requires the x- prefix for unrelated YAML nodes
x-zeek-template: &ZEEK_BASE
  image: zeektest:latest
  environment:
    ZEEK_DEFAULT_LISTEN_ADDRESS: "0.0.0.0"
  volumes:
    - ./zeekscripts:/usr/local/zeek/share/zeek/site/testing:z

x-zeek-controller: &ZEEK_CONTROLLER
  command: /usr/local/zeek/bin/zeek -j site/testing/controller.zeek
  ports:
    - "2150"

services:
  controller:
    <<: *ZEEK_BASE
    <<: *ZEEK_CONTROLLER

  client:
    image: zeektest:latest
    tty: true
